### ISSUE TITLE
Logentries Heroku add-on doesn't seem to log everything

### ISSUE THREAD

**Issue by annanhan** [rapid7/le_node#72] opened 2015-08-21 21:44 UTC
I have a node app and I'm using Logentries as a Winston transport. I am sending these logs to the Heroku add-on using the manual token TCP setup. I have noticed that some of the logs are not logged in the add-on. I can see the logs printed to the console and Papertrail. I ran through the debugger, and I can see the transport log line getting called. I've tried increasing the buffer size, but that doesn't seem to help. 

I added some debugging logs to see if it was a log level issue, but I don't think it is. The last three lines ("DONE WRITING", "returning refreshed data", and "this isn not going to print") are consistently not getting logged in Logentries.

I've tried playing with the time window and the live tail, but it still doesn't appear.

Attached are a couple of screenshots.

![921fda06bdc647bfd02a2d7eec034dbf](https://cloud.githubusercontent.com/assets/10620173/9419690/d82ea454-482b-11e5-80b5-f18bd424c5a6.png)

![235281ccad48423d1af66eab1d916c5b](https://cloud.githubusercontent.com/assets/10620173/9419688/d55b4840-482b-11e5-9d1f-250c83f8228d.png)

Any input would be appreciated.

Thanks,
Anna

**Comment by bathos** [comment] 2015-08-21 23:43
Hey Anna. Is it always those last three lines? If so, it would help to see the code where the log events are created and any possibly relevant context. My instinct initially was that it might be an issue with the application exiting before the write buffer had a chance to clear, but if it's getting to Papertrail, that's probably not it.

**Comment by annanhan** [comment] 2015-08-24 14:31
Sure. Below is the code. This is server code that has a couple of endpoints. One endpoint forces the server to fetch data and save the data. The second is to returned the stored data. The output I sent is from the former endpoint. The second endpoint logs look fine. 

Some code around the end of the first endpoint call:
![0394830e0ab19fb6cf0e1f2f80e0b7d6](https://cloud.githubusercontent.com/assets/10620173/9442604/b8950716-4a4a-11e5-81ca-fa94f8e5bde8.png)

Some code around the end of the second endpoint call:
![7ad8f130f4f748c2514f8e3fb8e7dfe0](https://cloud.githubusercontent.com/assets/10620173/9442662/083637e0-4a4b-11e5-8258-d7453e0c3c11.png)

Papertrail is just getting whatever logs are sent to the console. If you want me to try something to test out your initial instinct, we can do that.

Thanks.

**Comment by bathos** [comment] 2015-08-27 03:26
Thanks for the context. Leaves me scratching my head, though. There have been a number of issues in the past where it turned out I was doing something winston didn't like, so I might suggest trying to log directly with an le_node Logger instance in those places -- that would let us determine whether the issue is in the Logger or the Transport. Sorry I don't have anything more helpful to suggest yet -- it does look like an le_node bug to me, but I can't think of any situation yet where it might fail to log consistently in the same place yet also not emit an error.

**Comment by annanhan** [comment] 2015-08-27 17:50
I removed winston entirely, even from node_modules, and I get the same behavior:
![2426ff44a4192a643dd9e9901438cfdd](https://cloud.githubusercontent.com/assets/10620173/9528445/83ab09a4-4cc2-11e5-9834-113ac0d13d7a.png)
![5be0e2a9031b5a163d473957b77df86c](https://cloud.githubusercontent.com/assets/10620173/9528447/857275ce-4cc2-11e5-813d-33b1f912945a.png)

**Comment by annanhan** [comment] 2015-09-15 17:20
*bump* any traction on this? 
--thanks

**Comment by bathos** [comment] 2015-10-07 02:34
afraid not. I've been busy lately, but also I'm just not sure how to go about replicating it. Looking at the timestamps, it's rapid logging, but you said you already tried adjusting the max buffer size & anyway it would emit an error in that case. (In the examples, I don't see an error event handler on the logger, but I'm guessing there is one?)

I can't imagine it's the specific strings ... and with the async ops hitting external resources surely there'd end up being timing variation, so  ... and though what it *looks* like most is the script exiting before the data has all been written to the connection stream, but you said that this is server code.

This still brings us back to buffer issues, then, as the most likely culprit. The best test to provide confirmation of that would be to remove the INSIDE LOCK log call and see if, instead, you get the DONE WRITING one (and yet no others). It could be that le_node's recovery from a full buffer is broken.

**Comment by gearoidof-r7** [comment] 2016-08-30 15:10
this should be fixed in our new release

**Closed by gearoidof-r7** 2016-08-30 15:10 UTC
Labels: Bug, Wat
